apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: mongo-deployment
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
        - name: mongodb
          image: chaitanyavamsi/mongodb:v1
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: roboshop
spec:
  selector:
     project: roboshop
     component: mongodb
     tier: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017