apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: mongo-deployment
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
        - name: mongodb
          image: joindevops/mongodb:v1